import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated build output — regenerated by `npm run build:ds` and the
    // design-sync converter, so lint findings there aren't actionable.
    "dist/**",
    "ds-bundle/**",
    ".ds-sync/**",
  ]),
]);

export default eslintConfig;
